/*
 * Generated by Claude Code
 */
local g = import 'github.com/grafana/grafonnet/gen/grafonnet-latest/main.libsonnet';
local var = g.dashboard.variable;

{
  Datasource:
    var.datasource.new('Datasource', 'elasticsearch')
    + var.datasource.withRegex('/.*kube-burner.*/')
    + var.query.withRefresh(1)
    + var.query.selectionOptions.withIncludeAll(false)
    + var.query.selectionOptions.withMulti(false),

  platform:
    var.query.new('platform', '{"find": "terms", "field": "platform.keyword"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(2)
    + var.query.selectionOptions.withMulti(true)
    + var.query.selectionOptions.withIncludeAll(false)
    + var.query.generalOptions.withLabel('Platform'),

  sdn:
    var.query.new('sdn', '{"find": "terms", "field": "sdnType.keyword", "query": "platform.keyword: $platform"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(1)
    + var.query.selectionOptions.withMulti(true)
    + var.query.selectionOptions.withIncludeAll(false)
    + var.query.generalOptions.withLabel('SDN type'),

  clusterType:
    var.query.new('clusterType', '{"find": "terms", "field": "clusterType.keyword", "query": "platform.keyword: $platform"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(1)
    + var.query.selectionOptions.withMulti(true)
    + var.query.selectionOptions.withIncludeAll(true)
    + var.query.generalOptions.withLabel('clusterType'),

  job:
    var.query.new('job', '{"find": "terms", "field": "jobConfig.name.keyword", "query": "platform.keyword: $platform AND sdnType.keyword: $sdn AND clusterType.keyword: $clusterType AND NOT jobConfig.name: garbage-collection"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(1)
    + var.query.selectionOptions.withMulti(false)
    + var.query.selectionOptions.withIncludeAll(false)
    + var.query.generalOptions.withLabel('Job'),

  workerNodesCount:
    var.query.new('workerNodesCount', '{"find": "terms", "field": "workerNodesCount", "query": "platform.keyword: $platform AND sdnType.keyword: $sdn AND jobConfig.name.keyword: $job AND clusterType.keyword: $clusterType"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(1)
    + var.query.selectionOptions.withMulti(false)
    + var.query.selectionOptions.withIncludeAll(false)
    + var.query.generalOptions.withLabel('Workers'),

  ocpMajorVersion:
    var.query.new('ocpMajorVersion', '{"find": "terms", "field": "ocpMajorVersion.keyword", "query": "platform.keyword: $platform AND sdnType.keyword: $sdn AND jobConfig.name.keyword: $job AND workerNodesCount: $workerNodesCount AND clusterType.keyword: $clusterType"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(1)
    + var.query.selectionOptions.withMulti(true)
    + var.query.selectionOptions.withIncludeAll(true)
    + var.query.generalOptions.withLabel('OCP Major'),

  run_date:
    var.query.new('run_date', '{"find": "terms", "field": "endTimestamp", "query": "platform.keyword: $platform AND sdnType.keyword: $sdn AND jobConfig.name.keyword: $job AND workerNodesCount: $workerNodesCount  AND ocpMajorVersion.keyword: $ocpMajorVersion AND clusterType.keyword: $clusterType"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(2)
    + var.query.selectionOptions.withMulti(true)
    + var.query.selectionOptions.withIncludeAll(false)
    + var.query.generalOptions.withLabel('Run Date')
    + var.query.generalOptions.showOnDashboard.withNothing(),

  acs_version:
    var.query.new('acs_version', '{"find": "terms", "field": "labels.central_version.keyword", "query": "metricName.keyword: central_rox_central_info AND jobName.keyword: $job AND metadata.ocpMajorVersion.keyword: $ocpMajorVersion"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(2)
    + var.query.selectionOptions.withMulti(true)
    + var.query.selectionOptions.withIncludeAll(false)
    + var.query.generalOptions.withLabel('ACS Version'),

  uuid_from_date:
    var.query.new('uuid_from_date', '{"find": "terms", "field": "uuid.keyword", "query": "platform.keyword: $platform AND sdnType.keyword: $sdn AND jobConfig.name.keyword: $job AND workerNodesCount: $workerNodesCount  AND ocpMajorVersion.keyword: $ocpMajorVersion AND clusterType.keyword: $clusterType AND endTimestamp:$run_date"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(2)
    + var.query.selectionOptions.withMulti(true)
    + var.query.selectionOptions.withIncludeAll(true)
    + var.query.generalOptions.withLabel('UUID From Date')
    + var.query.generalOptions.showOnDashboard.withNothing(),

  uuid:
    var.query.new('uuid', '{"find": "terms", "field": "uuid.keyword", "query": "metricName.keyword: central_rox_central_info AND jobName.keyword: $job AND metadata.ocpMajorVersion.keyword: $ocpMajorVersion AND labels.central_version.keyword: $acs_version"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(2)
    + var.query.selectionOptions.withMulti(true)
    + var.query.selectionOptions.withIncludeAll(true)
    + var.query.generalOptions.withLabel('UUID from Version')
    + var.query.generalOptions.showOnDashboard.withNothing(),

  uuid_bkp:
    var.query.new('uuid_bkp', '{"find": "terms", "field": "uuid.keyword", "query": "platform.keyword: $platform AND sdnType.keyword: $sdn AND jobConfig.name.keyword: $job AND workerNodesCount: $workerNodesCount  AND ocpMajorVersion.keyword: $ocpMajorVersion AND clusterType.keyword: $clusterType"}')
    + var.query.withDatasourceFromVariable(self.Datasource)
    + var.query.withRefresh(2)
    + var.query.selectionOptions.withMulti(true)
    + var.query.selectionOptions.withIncludeAll(false)
    + var.query.generalOptions.withLabel('UUID')
    + var.query.generalOptions.showOnDashboard.withNothing(),

  compare_by:
    var.custom.new('compare_by', ['uuid'])
    + var.custom.generalOptions.withLabel('Compare by')
    + var.query.generalOptions.showOnDashboard.withNothing()
    + var.custom.selectionOptions.withIncludeAll(false)
    + var.custom.selectionOptions.withMulti(false),

  acs_component:
    var.custom.new('acs_component', ['central', 'central-db', 'sensor', 'collector', 'indexer', 'matcher', 'db', 'admission-control'])
    + var.custom.generalOptions.withLabel('ACS Component')
    + var.custom.selectionOptions.withIncludeAll(true)
    + var.custom.selectionOptions.withMulti(true),

  node_roles:
    var.custom.new('node_roles', ['masters', 'workers', 'infra'])
    + var.custom.generalOptions.withLabel('Node roles')
    + var.query.generalOptions.showOnDashboard.withNothing()
    + var.custom.selectionOptions.withIncludeAll(true)
    + var.custom.selectionOptions.withMulti(true),

}
