name: Grafana Importer
defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compile dashboards
      run: make build

    # The secret GRAFANA_URL must be set with the format http://username:password@url.org without a trailing /
    - name: Import dashboards to grafana
      run: >
        for t in rendered/**/*.json; do
        echo "Importing ${t}";
        dashboard=$(cat ${t});
        echo "{\"dashboard\": ${dashboard}, \"overwrite\": true}" |
        curl -k -Ss -XPOST -H "Content-Type: application/json" -H "Accept: application/json" -d@-
        "${{ secrets.GRAFANA_URL }}/api/dashboards/db" -o /dev/null;
        done 